### ISSUE TITLE
Calculator App (due date: 5 Nov 2019)

### ISSUE THREAD

**Issue by rishabhshuklax** [blurry-x-face/DailyFoss#1]
### Make a basic Calculator App using HTML, CSS and JavaScript

- [ ] It should do all BODMAS operations.

- [ ] UI should be responsive.

- [ ] Calculator should not break with any operation.

**Comment by baka-boi** [comment]
i want to do this

**Comment by dojutsu-user** [comment]
@baka-boi 
This issue is open for all. So, you can start working directly!!
Thanks a lot!!

**Comment by bajajvinamr** [comment]
#51  calculator uploaded

**Comment by bajajvinamr** [comment]
Status of #51 ?
