### ISSUE TITLE
Weather App (Web App, due date: 10 Nov.)

### ISSUE THREAD

**Issue by rishabhshuklax** [blurry-x-face/DailyFoss#3]
### Weather App Frontend

- [ ] Make the frontend of Weather App using [Open Weather API](https://openweathermap.org/api)

- [ ] It should have an input box which takes the city as input.

- [ ] It should display the current temperature and humidity of the given location.

**Comment by baka-boi** [comment]
i want to do this

**Comment by dojutsu-user** [comment]
@baka-boi 
This issue is open for all. So, you can start working directly!!
Thanks a lot!!
