### ISSUE TITLE
URL shortener (Due Date - Nov 11th)

### ISSUE THREAD

**Issue by Divy123** [blurry-x-face/DailyFoss#35]
- [ ] Make a URL shortener either using python or js.
 - [ ] The user should be able to enter the original URL using form on a web app and the result should be the shortened URL.
 - [ ] The UI should look beautiful and responsive.
 - [ ] Also, proper routes should be present.

**Comment by lav-joshi** [comment]
i want to do thsi

**Comment by blank-27** [comment]
I want to claim this issue

**Comment by Divy123** [comment]
Assigned to @lav-joshi

**Comment by Divy123** [comment]
These issues are open to all.
