### ISSUE TITLE
Article on various networking protocols used in back-end web development.(Due Date - Nov 9)

### ISSUE THREAD

**Issue by Divy123** [blurry-x-face/DailyFoss#38]
- [ ] Write an article on Medium platform of approximately 3 minute read on various protocols used in back-end web development like HTTP, HTTPS, FTP, SMTP etc.

 - [ ] Share a link here of your draft and don't publish before we merge your PR. The PR is nothing but a single file containing the link of your article.

**Comment by lav-joshi** [comment]
i want to do this

**Comment by lav-joshi** [comment]
please assign sir

**Comment by HarshTiwari1234321** [comment]
i wan to do this .. 
assign me...

**Comment by dojutsu-user** [comment]
Assigned to: @lav-joshi
