### ISSUE TITLE
Explore chrome developer tools and write an article (Due Date - Nov 9)

### ISSUE THREAD

**Issue by Divy123** [blurry-x-face/DailyFoss#39]
- [ ] Explore chrome dev tools and write an article of approximately 3 minute read on the same.

 - [ ] The same should be written on Medium and the PR should contain a single file containing your link. Don't publish your article without getting the PR merged.

**Comment by yk1ax** [comment]
@Divy123 I want to claim this issue

**Comment by lav-joshi** [comment]
i want to do this

**Comment by Divy123** [comment]
Assigned to @yk1ax

**Comment by yk1ax** [comment]
@Divy123 I have created a pull request for this issue. You can review it.

**Comment by Divy123** [comment]
Please provide the link to your PR here.

**Comment by yk1ax** [comment]
@Divy123 Link to my PR for this issue : [Chrome DevTools Article PR](https://github.com/blurry-x-face/DailyFoss/pull/52)

**Comment by sachin746** [comment]
i want to do this

**Comment by yk1ax** [comment]
@dojutsu-user my PR wasn't merged before closing this issue ?

**Comment by dojutsu-user** [comment]
@yk1ax Not a problem.

**Comment by yk1ax** [comment]
@dojutsu-user so my PR wasn't accepted ?
