### ISSUE TITLE
Login Page UI(due date: 5 Nov.)

### ISSUE THREAD

**Issue by rishabhshuklax** [blurry-x-face/DailyFoss#4]
### Login Page UI

- [ ] The UI Should be responsive.

- [ ] UI should look good.

**Comment by blank-27** [comment]
I want to claim this issues

**Comment by Divy123** [comment]
This issue is open for all. So, you can start working directly!!
Thanks a lot!!

**Comment by MightyMoin** [comment]
i want to do this

**Comment by Divy123** [comment]
The deadline is over and the issue stands closed.
