### ISSUE TITLE
Make an audio player using Spotify API (Due Date - 11 Nov)

### ISSUE THREAD

**Issue by Divy123** [blurry-x-face/DailyFoss#40]
- [ ] Make an audio player web app using Spotify API.
 - [ ] The app should be able to play, pause, search songs using the API.
 - [ ] The issue is PRO but can fetch extra 20 points  i.e. 70 points if the information searched is stored in the Database as well. (You may use MySQL, Postgres or MongoDB as DBMS).

**Comment by lav-joshi** [comment]
i want to do this

**Comment by blank-27** [comment]
I want to claim this issue

**Comment by Divy123** [comment]
These issues are open for everyone. So you both can do it.
