### ISSUE TITLE
Documentation for Placement Cell website (Due Date: Nov 8th)

### ISSUE THREAD

**Issue by Divy123** [blurry-x-face/DailyFoss#41]
- [ ]  Visit Placement cell website and write a brief documentation of the same.
 - [ ] This should be a single MD file.

**Comment by lav-joshi** [comment]
i want to do this

**Comment by Divy123** [comment]
Assigned to @lav-joshi

**Comment by bajajvinamr** [comment]
Sir is this issue open to everyone?

**Comment by Divy123** [comment]
Yes...
